name = "Violette Belle"
license = ""
licenselink = ""
description = "Clean, responsive one-page portfolio accompanied by a minimalist blog."
homepage = ""
tags = ["blog", "portfolio", "gallery", "minimalist", "responsive", "flexbox"]
features = ["blog", "portfolio", "google analytics"]
min_version = "0.5"

[author]
  name = "Susannah Fisher"
  homepage = "https://susannahfisher.art"
